Corrected post date as pointed out by maintainer
opennic/opennic-web pull request #73
Opened 2020-08-23 21:40 UTC by hack13

2020-08-24 15:43 UTC, Fusl requested changes

2020-08-24 15:43 UTC, Fusl commented on _i18n/en/_posts/2020-08-21-ns1-&-ns2.va.us.dns.opennic.glue-maintenance.md
> +date: 2020-06-29
month and day are wrong as well, please correct those

2020-08-25 10:25 UTC, hack13 commented
Sorry... changes made... I will double check my work before committing in the future...

2020-08-25 14:23 UTC, Fusl approved these changes

2020-08-25 14:23 UTC, merged